### ISSUE TITLE
Syntax error 

### ISSUE THREAD

**Issue by zikramuddeen** [dante4rt/evm-bruteforce#1]
I am getting a syntax error in index.js and also in indexV2.js , I will attach screenshot of my system ![Screenshot_2023-12-27-14-33-26-245_com.realvnc.viewer.android.jpg](https://github.com/dante4rt/evm-bruteforce/assets/90516806/df6cfc82-969c-4d84-b6d5-44e267662a57)

**Comment by dante4rt** [comment]
Can you share your Node version? I think that's the problem.

Reference :
https://github.com/wechaty/getting-started/issues/204
